# fcitx envs
env=GTK_IM_MODULE,fcitx
env=QT_IM_MODULE,fcitx
env=QT_IM_MODULES,wayland;fcitx
env=SDL_IM_MODULE,fcitx
env=XMODIFIERS,@im=fcitx
env=GLFW_IM_MODULE,ibus

# Start fcitx5 input method
exec-once=fcitx5 -d &

# DMS shell
exec-once=dbus-update-activation-environment --systemd --all
exec-once=systemctl --user start mango-session.target

# Custom config
enable_hotarea=0
sloppyfocus=0 # Focus doesn't follow mouse
no_border_when_single=1

# Gemini-CLI scratchpad
windowrule=isnamedscratchpad:1,width:600,height:700,offsetx:110,offsety:0,isoverlay:1,appid:foot-gemini
bind=SUPER,s,toggle_named_scratchpad,foot-gemini,none,foot --app-id foot-gemini -D "/home/shadowprogr/gemini-cli/" "/home/shadowprogr/.local/share/mise/installs/node/24.14.0/bin/gemini"

source=./keybinds.conf
source=./windowrules.conf
source=./hardware-specific.conf
source=./dms/outputs.conf
source=./dms/layout.conf
source=./dms/colors.conf
source=./dms/cursor.conf
