# Terminal rules
windowrule=isterm:1,appid:foot
windowrule=unfocused_opacity:0.85,appid:foot
windowrule=focused_opacity:1.0,appid:foot

# Floating windows
windowrule=isfloating:1,appid:org.quickshell
windowrule=isfloating:1,appid:btrfs-assistant

windowrule=isfloating:1,isglobal:1,isoverlay:1,title:Picture-in-Picture
