# =========================================================
# WINDOW RULES
# =========================================================
# Terminal
windowrule=focused_opacity:1.0,unfocused_opacity:0.85,isterm:1,appid:foot

# Floating windows
windowrule=isfloating:1,appid:org.quickshell
windowrule=isfloating:1,appid:btrfs-assistant

# PiP windows
windowrule=isfloating:1,isglobal:1,isoverlay:1,isnoborder:1,width:400,height:225,offsetx:97,offsety:95,title:Picture-in-Picture
windowrule=isfloating:1,isglobal:1,isoverlay:1,isnoborder:1,width:400,height:225,offsetx:97,offsety:95,title:Picture in Picture

# Tag assignment
windowrule=tags:2,appid:org.mozilla.firefox
windowrule=tags:3,appid:cursor
windowrule=tags:4,appid:vesktop
windowrule=tags:4,appid:slacky

source-optional=./pwa-rules.conf

# =========================================================
# TAG RULES
# =========================================================
# Tag 1 is for terminal tiling
tagrule=id:1,layout_name:tile
# Tag 2 is for browsers
tagrule=id:2,layout_name:scroller
# Tag 3 is for IDEs
tagrule=id:3,layout_name:scroller
# Tag 4 is for communication apps
tagrule=id:4,layout_name:scroller
# Tag 5 is for dual master tiling (monitoring stuff)
tagrule=id:5,layout_name:tile,nmaster:2

# Tag 6-8 TBD, probably will use them to host speficic media apps

# Tag 9 is floating only
tagrule=id:9,open_as_floating:1

# =========================================================
# LAYERS RULES
# =========================================================
# Placeholder for now
